### ISSUE TITLE
Stopping and starting services is slooooow

### ISSUE THREAD

**Issue by steveoh** [agrc/forklift#118]
### Steps to reproduce
1. update date that affects multiple services
2. wait
3. keep waiting
### Expected behavior

I think the stop and start behavior should be in [parallel](http://stackoverflow.com/questions/9786102/how-do-i-parallelize-a-simple-python-loop#9786225)
### Actual behavior

It's synchronous.

**Comment by stdavis** [comment]
👍

**Comment by steveoh** [comment]
So, Is it done yet?

![waiting](https://media.giphy.com/media/kVRBvsiOyBM8o/giphy.gif)
