### ISSUE TITLE
Detect field length schema changes

### ISSUE THREAD

**Issue by stdavis** [agrc/forklift#12]
### Steps to reproduce
Try to update a feature class that has a longer text field in source than in destination (same name).

### Expected behavior
I would expect the tool to warn me about the different in field length but it doesn't.

### Actual behavior
No schema change error is reported.

We should look at field type, length, scale and precision.

Ported from https://github.com/agrc/agrc.python/issues/3.

**Comment by stdavis** [comment]
Looks like we don't need to worry about scale & precision for file geodatabases. From the [help doc](http://desktop.arcgis.com/en/arcmap/10.3/tools/data-management-toolbox/add-field.htm)
>Personal and file geodatabases support only binary type fields, and precision and scale are ignored.

**Comment by stdavis** [comment]
`arcpy.Append_management(fc1, fc2, 'TEST')` does not catch string field length differences. :(

**Comment by steveoh** [comment]
you can get at that from a [describe](http://desktop.arcgis.com/en/arcmap/latest/analyze/arcpy-functions/table-properties.htm) and then the [fields](http://desktop.arcgis.com/en/arcmap/latest/analyze/arcpy-classes/field.htm) property.
