### ISSUE TITLE
Static Data

### ISSUE THREAD

**Issue by stdavis** [agrc/forklift#131]
There are several datasets in staging that are not created as outputs of pallets. These should be moved somewhere else so that we can delete and recreate everything in staging without worry of losing anything important. This will be helpful when we want to remove pallets and services.

Here's a list of all of the static data that I know of:
- ~~[ ] Address locators in `locators.gdb`~~
- [x] `bbecon.gdb`
- [x] `deqreferencedata.gdb` (this will be part of the dwq upgrade)
- ~~[ ] `locators_.gdb` (backup for the other)~~
- ~~[ ] `surfacewaterquality.gdb` (this project is likely going to be deprecated soon, so not worth the trouble)~~
- [x] `drg.gdb`

Maybe we need a `staging-static` folder?

**Comment by steveoh** [comment]
I think locators_.gdb is there to always have functional locators with the idea that we could delete an invalid locator, copy it from here, and rebuild hopefully successfully.

**Comment by stdavis** [comment]
Or maybe we need a geodatabase in production that's called `StaticData.gdb` or something and we just maintain it in production. If forklift doesn't touch this data then maybe we should keep it out of the picture and just put it in production in a place that's obvious that forklift doesn't touch it.

**Comment by stdavis** [comment]
This is what we decided to do to address this (please correct me if I'm wrong):
- [ ] Move all of the data listed above into it's respective repositories. I'm assuming that the locators data should go into the `agrc/warehouse` repo?
- [ ] Create a new property of a pallet called `static_data: String[]` that defines the static data for a project. When forklift runs it will check for the existence of this data in production. If it's not there then it will move it directly to prod (not worrying about shutting down services since there can't be a service pointed at it if there's no data there).
- [ ] In the future when there are data changes, we just need to update the repo and manually update the data in production. Or we could create a new method for forklift called `update-static <some pallet>` and have it shut down the services and update the data. Thoughts on this item?

**Comment by steveoh** [comment]
I like it all.

**Comment by stdavis** [comment]
I've got my part of this issue complete. Let me know if you want help with locators.

**Comment by stdavis** [comment]
I used up our quota for LFS on GitHub with ironing-board and deq-enviro. We need to come up with another solution for where to stick static data.

**Comment by stdavis** [comment]
What about keeping the data in `C:\Scheduled\static` on the server? Then we could point `static_data` to that?

**Comment by steveoh** [comment]
yeah LFS is not going to work.
