### ISSUE TITLE
del acts strangely with dictionary

### ISSUE THREAD

**Issue by keatonwalker** [agrc/forklift#142]
### Steps to reproduce
1. Create a dictionary with a lot of keys
1. Watch memory usage increase
1. del all the keys and the memory usage stays the same.

We may want to [track un-accessed](https://github.com/agrc/forklift/blob/ff547811edf2f8a08422a5894123391d684b3fa9/src/forklift/core.py#L281-L283) hashes another way.

**Comment by steveoh** [comment]
Things to try

- [ ] pop
- [ ] insert into another dict and handle in [determine deletes](https://github.com/agrc/forklift/blob/ff547811edf2f8a08422a5894123391d684b3fa9/src/forklift/models.py#L309-L310)

**Comment by stdavis** [comment]
I'm likely the idea of a mysql database more and more...

**Comment by stdavis** [comment]
Closed with 14d6782.
