### ISSUE TITLE
compact gdb's after truncate and append

### ISSUE THREAD

**Issue by steveoh** [agrc/forklift#15]
williamscraigm: do you run [compact](http://desktop.arcgis.com/en/arcmap/latest/tools/data-management-toolbox/compact.htm#GUID-5B606FF4-8A90-4EE0-83AE-23D5238FC9BA) on it after doing that? if you're doing lots of updates and don't compact, all the changes are in delta files and it's not optimal.

**Comment by steveoh** [comment]
it appears that the compact might not be working. supposedly if there are `*.freelist` files the compact is not completing. I wonder if we need to stop all of the services in server or uncheck the lock schema box on all the services using the geodatabase.

**Comment by stdavis** [comment]
[Here's where it runs currently](https://github.com/agrc/mapserv-data-update/blob/8fc3330c90d094b1e4165888b6b63294db5330cf/main.py#L54)

These are the `*.freelist` files that I saw this morning when I first logged on:
![image](https://cloud.githubusercontent.com/assets/1326248/15428403/6df9f576-1e58-11e6-9427-35c1da52a63f.png)

I then stopped both servers and ran a compact. This is what it looked like afterwards:
![image](https://cloud.githubusercontent.com/assets/1326248/15428454/a6a8d522-1e58-11e6-924c-06f149697ef3.png)

Not much different. And the files are pretty small to begin with.
