### ISSUE TITLE
if destination coordinate system is set after crates are added it is ignored

### ISSUE THREAD

**Issue by steveoh** [agrc/forklift#162]
## Works
```py
class SmallDataPallet(Pallet):

    def __init__(self):
        super(SmallDataPallet, self).__init__()

        self.destination_coordinate_system = 26911
        self.add_crate('Counties', {'source_workspace': source_workspace, 'destination_workspace': destination_workspace})
```

## Does not work
```py
class SmallDataPallet(Pallet):

    def __init__(self):
        super(SmallDataPallet, self).__init__()

        self.add_crate('Counties', {'source_workspace': source_workspace, 'destination_workspace': destination_workspace})
        self.destination_coordinate_system = 26911
```

Also if you change the coordinate system the transform does not get removed and can cause issues.

**Comment by stdavis** [comment]
Making the setting of `destination_coordinate_system` before the adding of crates a requirement seems reasonable to me. I'm not sure that I would have expected your second example to work. Would you be OK if we added something to the docs?

The issue with the transform not getting cleared seems like a legit issue to me. Any ideas on how to deal with it? Just doc that you need to make sure that handle it within the pallet? I'm not sure that we want to add yet another method to the pallet for changing the coordinate system.

**Comment by steveoh** [comment]
set it before adding pallets. 🔨 ⬇️
