### ISSUE TITLE
Return crate warning for duplicate features

### ISSUE THREAD

**Issue by stdavis** [agrc/forklift#185]
I don't think that we need to log the actual duplicate features. Just return a warning in the report so that we can alert the data steward. Then they can find the duplicate features themselves.

**Comment by steveoh** [comment]
Do you think it is possible to have it display this warning as well as data updated? It's difficult now to tell what data was updated since all of the data basically has duplicates.

**Comment by stdavis** [comment]
Ya, I've noticed this problem as well. We need to figure out how to display both. I'll reopen the issue.

**Comment by stdavis** [comment]
More information:
We have lots of code like this:
```python
updated_crates = [crate for crate in self.get_crates() if crate.result[0] in [Crate.CREATED, Crate.UPDATED]]
```
This means that if there's duplicate features, the crate will not make it into `updated_crates` since the result is different even if the data was updated. If I add `Crate.WARNING` to the list, then crates with duplicate features would be in `update_crates` every time even if their data was not updated.

I think that we need to move `WARNING` out of `crate.result[0]` and store it somewhere else.
