### ISSUE TITLE
Copy errors not showing up in report

### ISSUE THREAD

**Issue by stdavis** [agrc/forklift#202]
### Steps to reproduce
Not sure yet. Perhaps run a pallet that has no errors other than copying to `copy_data`? [Here's a link to the log file](https://www.dropbox.com/s/v2jjbwoowzd6cv0/forklift.log.1?dl=0).

### Expected behavior
We should see the copy error in the report.

### Actual behavior
![image](https://user-images.githubusercontent.com/1326248/29317242-3ba59bf4-8188-11e7-8185-3fb9d0dbb4fb.png)
Perhaps the red line at the top is the error but the error message is missing?

**Comment by steveoh** [comment]
Isn't this done?

**Comment by stdavis** [comment]
Not that I know of. The red line happened to be something else not related to this issue.

**Comment by stdavis** [comment]
I wasn't able to reproduce this at the current version of forklift today. So I'm closing for now.
