### ISSUE TITLE
the big split

### ISSUE THREAD

**Issue by steveoh** [agrc/forklift#235]
I started the big split and I want some help so yins know what is going on and keep some investment in forklift. 

A few little things that should be pretty simple to pick off...

1. static data is only copied if there are changes to the crate data. Probably not ideal, but I don’t think we want to shut down the servers to copy static data every time if there were no changes
1. the report object is a bit wonky with static_success. Statics aren’t a crate, but I think we should treat them similar in regards to the report
1. the cli option for update static data needs to be reworked and is continent upon the first thing mentioned

otherwise i think the left side of the grand canyon is looking ok.

I've been fooling with it using

`python -m forklift lift c:\Projects\GitHub\forklift\samples\TypicalPallet.py`

and a config.json like

```json
{
    "configuration": "Production",
    "shipTo": ["c:\\forklift\\data\\production"],
    "dropoffLocation": "c:\\forklift\\data\\receiving",
    "hashLocation": "c:\\forklift\\data\\hashed",
    "warehouse": "c:\\forklift\\warehouse",
    "notify": [
        "noone@utah.gov"
    ],
    "repositories": [],
    "sendEmails": false,
    "servers": {
        "options": {
            "username": "user",
            "password": "test",
            "protocol": "http",
            "port": 6080
        },
        "primary": {
            "machineName": "not.necessary.yet"
        }
    },
    "email": {
        "smtpServer": "yada.yada",
        "smtpPort": 25,
        "fromAddress": "noreply@utah.gov"
    },
    "poolProcesses": 20
}
```

**Comment by stdavis** [comment]
I'll take a stab at some point today.

**Comment by stdavis** [comment]
And by today, I meant Monday. Just didn't get to it today...

**Comment by stdavis** [comment]
> 1. static data is only copied if there are changes to the crate data. Probably not ideal, but I don’t think we want to shut down the servers to copy static data every time if there were no changes

I'm struggling with static data. It just doesn't fit very well within forklift. Maybe we should strip it out of the pallets and just manage it manually? We could manually drop it in the drop off folder when we want it pushed to production?

**Comment by stdavis** [comment]
Or maybe we need a static dropoff folder?

**Comment by steveoh** [comment]
i'm going to close this. we should open some new ones to track what is going on...
