### ISSUE TITLE
cli._process_packing_slip should know the status of the data copy

### ISSUE THREAD

**Issue by steveoh** [agrc/forklift#238]
`_process_packing_slip` reads the packing slip and builds all pallets in the slip regardless if the data copied successfully. 

### Proposal

1. update `cli._generate_packing_slip` to output the workspace name of the output.
1. update `cli.ship_data` to read the packing slip information earlier in the method and update the slip's crate property by matching on the workspace name and adding a copy successful property
1. do the same thing for starting and stopping the servers. Use the the slip to track status
1. finally update `_process_packing_slip()` to take the messages into account when building the pallets and only build the ones that copied successfully

👍 if you like this or comment to modify

**Comment by stdavis** [comment]
I don't think that we need to track the copy status on a crate level, do we? `post_copy_process` is a pallet-level method. Don't we just need to track if the copy was successful at the pallet level?

**Comment by stdavis** [comment]
> So use the copy data array to match affected pallets?

Yes.
