### ISSUE TITLE
forklift parody 

### ISSUE THREAD

**Issue by steveoh** [agrc/forklift#243]
![image](https://user-images.githubusercontent.com/325813/46423176-3bf40300-c6f3-11e8-9ab6-32d78edca9e6.png)

https://xkcd.com/2054/

**Comment by stdavis** [comment]
Definitely readme worthy. :)

**Comment by stdavis** [comment]
![gif](https://media.giphy.com/media/N35rW3vRNeaDC/giphy.gif)
