### ISSUE TITLE
Resolve need to revert git changes after test run

### ISSUE THREAD

**Issue by steveoh** [agrc/forklift#246]
since tox is no longer running our tests in virtual environments the test data in our source controlled location is being modified and fouling up git. It is cumbersome to revert the changes after every test run. Consider alternatives.

The only idea that comes to mind for me is to copy the data to another location and work on it there and then delete it.

pytest has a tempdir feature that could be useful https://docs.pytest.org/en/latest/reference.html#tmpdir

This is open for discussion so comment away!

**Comment by stdavis** [comment]
I haven't had data updates show up after running tests for a while. Are you still seeing them?

**Comment by steveoh** [comment]
every time. 41 files. tests\config.json and tests\scratch.gdb

**Comment by stdavis** [comment]
I wasn't getting this on Tuesday but I'm seeing the same thing this morning. scratch.gdb is created dynamically so we should be able to clean that up. I'm going to try to tackle this issue...

**Comment by stdavis** [comment]
I'll include this in my next PR...
