### ISSUE TITLE
Duplicate pallets in report

### ISSUE THREAD

**Issue by steveoh** [agrc/forklift#258]
Certain pallets are being executed twice or reported twice. Investigate

![image](https://user-images.githubusercontent.com/325813/47169827-bdd25780-d2c1-11e8-88ab-f0a9e87afe57.png)

**Comment by stdavis** [comment]
I found both `starch` and `ironing-board` folders in the warehouse in addition to `locate` and `broadband`. I've removed the former folders.

I also found this in `crash-db`:
![image](https://user-images.githubusercontent.com/1326248/47306960-0607b780-d5eb-11e8-9842-3cd47c7e535b.png)

I'll remove the `__pycache__` folder just in case this is causing issues although I wouldn't think so.

**Comment by stdavis** [comment]
I also confirmed that there are no duplicates in the config.

**Comment by stdavis** [comment]
I believe that we have this solved.
