### ISSUE TITLE
shipping external items

### ISSUE THREAD

**Issue by steveoh** [agrc/forklift#263]
It would be nice to be able to drop data into a folder and have it shipped the next time forklift runs.

I think we could create another folder that ship will be made aware of and merges that data with the items in the drop off location. It will be deleted after it is copied.

I propose we call the folder `one-time`.

What do you all think?

**Comment by stdavis** [comment]
I'm good with it. It does remove the possibility of manually placed data from being deleted from the dropoff folder.

**Comment by stdavis** [comment]
I believe that this use is now satisfied. And FGDBs dropped into the receiving folder will be shipped on the next run. Please reopen if I'm not understanding the original use case.
