### ISSUE TITLE
Split out SGID

### ISSUE THREAD

**Issue by steveoh** [agrc/forklift#27]
### Steps to reproduce
1. Are we going to split out the SGID10.gdb in the pallets or handle it magically in 🚜?

### Expected behavior
A crate can ask for sgid10.boundaries.counties or counties and the county feature class will end up in a boundaries.gdb?

### Actual behavior
Everything ends up in SGID10.gdb

**Comment by stdavis** [comment]
Maybe we should keep everything in SGID10.gdb for now so that we don't have to republish all of the services.

**Comment by steveoh** [comment]
We're republishing anyway and we are doing this.

**Comment by stdavis** [comment]
This can be closed, can't it?

**Comment by steveoh** [comment]
Yup
