### ISSUE TITLE
dunderscore Pallet

### ISSUE THREAD

**Issue by steveoh** [agrc/forklift#28]
### Steps to reproduce
1. use dunderscore `__` for all pallet properties and private methods
### Expected behavior

Avoid unexpected overwrites when creating your own pallet
### Actual behavior

💥 Collide all the things.

**Comment by steveoh** [comment]
maybe this was paranoia :eyes: but there seems to only be `_crates`. Most of the important things that have common names that could get overridden are on the Crate class and we don't inherit from that class.

**Comment by stdavis** [comment]
@steveoh Can this be closed? I'm thinking that we are OK keep the single underscore.

**Comment by steveoh** [comment]
I think we've done well so far without this so yup. It was paranoia.
