### ISSUE TITLE
Default geographic transformation breaks project if source is not 26912

### ISSUE THREAD

**Issue by stdavis** [agrc/forklift#281]
### Steps to reproduce
1. Set up a crate to point to a source that is not 26912 without setting any destination coordinate system or geographic transformation.

### Expected behavior
The output is projected to 3857 with whatever default geographic transformation that Esri chooses when one isn't passed into the Project tool.

### Actual behavior
The pallet fails with `ERROR 000365: Invalid geographic transformation.` because it attempts to use `NAD_1983_To_WGS_1984_5` which is specific to the from and to datums for 26912 -> 3857.

Perhaps we should not default to `NAD_1983_To_WGS_1984_5` and make that a requirement of the pallet if you really want to use that one? This would require us to add it to all pallets that care about that level of accuracy.

**Comment by steveoh** [comment]
I'd rather only modify pallets that have special needs. 

Since we set likely defaults and allow those to be modified, my vote is that we do nothing.

**Comment by stdavis** [comment]
Likely defaults only for those of us that use `26912`. But yes, I can understand happy-pathing for our systems.
