### ISSUE TITLE
Migrate upgrade scripts

### ISSUE THREAD

**Issue by steveoh** [agrc/forklift#29]
### Scripts to Update
From windows scheduler on .56
- [x] [Parcels](https://github.com/agrc/Parcels/blob/master/scripts/Pallet.py)
- [x] [ACTSStatisticsViewer](https://github.com/agrc/warehouse/blob/master/svn/agrc-acts-statistics/ActsPallet.py)
- [x] ArchSitesUpdate
- [x] bb-econ
- [x] [DDACTS](https://github.com/agrc/Crash-db/pull/1)
- [x] deq-enviro (nightly & hourly)
- [x] FiberVerification
- [x] broadband (residential)
- [x] UpdateOGMData
- [x] UpdateRasterData
- [x] updateReports (roadkill)

### Michael's scripts
All are daily unless otherwise noted
- [x] SGID10 (Saturday mornings)
- [x] [udnr](https://github.com/agrc/warehouse/tree/master/database_maintenance/UDNR)
- [x] [udpr](https://github.com/agrc/warehouse/tree/master/database_maintenance/UDPR)
- [x] [FFSL](https://github.com/agrc/warehouse/tree/master/database_maintenance/FFSL)
- [x] udwr
- [x] UEMP
- [x] uggp
- [x] ughp
- [x] ugio
- [x] UTAX
- [x] utrans

### Other services that use data in a fgdb and may or may not have nightly scripts
- [x] UtahEM (All data in UDES.gdb)

The rest of these are in SGID10.gdb...
- [x] BBEcon/MapService.MapServer": ["AirportLocations",
        "Schools",
        "HealthCareFacilities",
        "ZoomLocations",
        "NaturalGasService_Approx",
        "RetailCulinaryWaterServiceAreas",
        "ElectricalService",
        "RuralTelcomBoundaries",
        "LightRailStations_UTA",
        "LightRail_UTA",
        "EnterpriseZones",
        "CommuterRailStations_UTA",
        "CommuterRailRoutes_UTA"
    ]
- [x] [BEMS/Boundaries.MapServer": ["EMSServiceAreas"]](https://github.com/agrc/BEMS/blob/master/scripts/BemsPallet.py)
- [x] BaseMaps/AddressPoints.MapServer": ["AddressPoints"]
- [x] BaseMaps/Hillshade.MapServer": ["Roads",
        "Municipalities_Carto",
        "Counties",
        "ZoomLocations",
        "PlaceNamesGNIS2000"
    ]
- [x] BaseMaps/Hybrid.MapServer": ["Roads",
        "Municipalities_Carto",
        "Counties",
        "ZoomLocations",
        "PlaceNamesGNIS2000"
    ]
- [x] BaseMaps/Lite.MapServer": ["Roads",
        "Municipalities_Carto",
        "Counties",
        "ZoomLocations",
        "PlaceNamesGNIS2000"
    ]
- [x] BaseMaps/Terrain.MapServer": ["Roads",
        "Municipalities_Carto",
        "Counties",
        "ZoomLocations",
        "PlaceNamesGNIS2000"
    ]
- [x] BaseMaps/Topo.MapServer": ["Roads",
        "Municipalities_Carto",
        "Counties",
        "ZoomLocations",
        "PlaceNamesGNIS2000"
    ]
- [x] BaseMaps/Vector.MapServer": ["Roads",
        "Municipalities_Carto",
        "Counties",
        "ZoomLocations",
        "PlaceNamesGNIS2000"
    ]
- [x] Broadband/ExportWebMap.GPServer": ["Utah"]
- [x] Broadband/ProviderCoverage.MapServer": ["ZoomLocations",
        "PopBlockAreas2010_Approx"
    ]
- [x] DEM.ImageServer": ["DEM_10METER"]
- [x] DEQEnviro/MapService.MapServer": ["LandOwnership",
        "ICBUFFERZONES",
        "HUC",
        "Counties"
    ]
- [x] DEQEnviro/Secure.MapServer": ["Counties"]
- [x] DEQSpills.MapServer": ["BFNONTARGETED",
        "BFTARGETED",
        "SITEREM",
        "NPL",
        "EWA",
        "FUD",
        "MMRP",
        "TIER2",
        "TRI",
        "FACILITYUST",
        "VCP",
        "EnvironmentalIncidents"
    ]
- [x] Hava.MapServer": ["UtahHouseDistricts2012",
        "UtahSenateDistricts2012",
        "USCongressDistricts2012",
        "ZipCodes",
        "Counties",
        "VistaBallotAreas",
        "VistaBallotAreas_Proposed",
        "Parcels_Beaver",
        "Parcels_BoxElder",
        "Parcels_Cache",
        "Parcels_Carbon",
        "Parcels_Daggett",
        "Parcels_Davis",
        "Parcels_Duchesne",
        "Parcels_Emery",
        "Parcels_Grand",
        "Parcels_Iron",
        "Parcels_Juab",
        "Parcels_Kane",
        "Parcels_Millard",
        "Parcels_Morgan",
        "Parcels_Piute",
        "Parcels_Rich",
        "Parcels_SaltLake",
        "Parcels_SanJuan",
        "Parcels_Sanpete",
        "Parcels_Summit",
        "Parcels_Tooele",
        "Parcels_Uintah",
        "Parcels_Utah",
        "Parcels_Wasatch",
        "Parcels_Washington",
        "Parcels_Wayne",
        "Parcels_Weber",
        "AddressPoints"
    ]
- [x] LandUsePlanning.MapServer": ["QuaternaryFaults",
        "Municipalities",
        "WildernessProp_WDesert1999",
        "LakesNHDHighRes",
        "ConservationEasements",
        "Cemeteries",
        "HealthCareFacilities",
        "Schools",
        "Libraries",
        "PlaceNamesGNIS2000",
        "HistoricDistricts",
        "AvalanchePaths",
        "LandslideAreas",
        "LandSlidePotential",
        "LandOwnership",
        "LiquefactionPotential",
        "ParagonahFloodZones",
        "Floodplains",
        "SummitCoFloodZones",
        "WeberCoFloodZones",
        "Watersheds_Area",
        "SpringsNHDHighRes",
        "Streams",
        "Wetlands",
        "Airports",
        "Railroads",
        "Roads",
        "DominantVegetation",
        "Soils",
        "WaterRelatedLandUse",
        "Parcels_Weber",
        "Parcels_Wayne",
        "Parcels_Washington",
        "Parcels_Wasatch",
        "Parcels_Utah",
        "Parcels_Uintah",
        "Parcels_Tooele",
        "Parcels_Summit",
        "Parcels_Sanpete",
        "Parcels_SanJuan",
        "Parcels_SaltLake",
        "Parcels_Rich",
        "Parcels_Millard",
        "Parcels_Juab",
        "Parcels_Iron",
        "Parcels_Grand",
        "Parcels_Emery",
        "Parcels_Davis",
        "Parcels_Carbon",
        "Parcels_Daggett",
        "Parcels_Cache",
        "Parcels_BoxElder",
        "Parcels_Beaver",
        "PLSSTownships_GCDB",
        "PLSSSections_GCDB",
        "Habitat_Muledeer",
        "Habitat_Pronghorn",
        "Habitat_RingNeckedPheasant",
        "Habitat_RockyMountainElk",
        "SchoolDistricts"
    ]
- [x] LtGovPoliticalDistricts/Districts.MapServer": ["USCongressDistricts2012",
        "UtahSenateDistricts2012",
        "UtahHouseDistricts2012",
        "UtahSchoolBoardDistricts2012"
    ]
- [x] LtGovPoliticalDistricts/Labels.MapServer": ["USCongressDistricts2012",
        "UtahSenateDistricts2012",
        "UtahHouseDistricts2012",
        "UtahSchoolBoardDistricts2012"
    ]
- [x] OilGasMining.MapServer": ["DNROilGasWells",
        "Counties",
        "StreamsNHDHighRes",
        "DNROilGasFields",
        "DNROilGasUnits"
    ]
- [x] [PLSS.MapServer": ["PLSSPoint_AGRC", "Counties"]](https://github.com/agrc/PLSS/blob/master/scripts/PLSSPallet.py)
- [x] PoliticalDistricts.MapServer": ["UtahHouseDistricts2012",
        "UtahSenateDistricts2012",
        "DistrictCombinationAreas2012"
    ]
- [x] Roadkill/Overlays.MapServer": ["UDOTMileposts"]
- [x] Roadkill/Toolbox.GPServer": ["UDOTRoutes_LRS"]
- [x] SGID/CountyBoundaries.MapServer": ["Counties"]
- [x] SGID/DOGM.MapServer": ["DNROilGasWells_HDPath"]
- [x] SGID/LandOwnership.MapServer": ["LandOwnership"]
- [x] Socrata.MapServer": ["Municipalities",
        "UtahSenateDistricts2012",
        "UtahHouseDistricts2012",
        "UtahSchoolBoardDistricts2012",
        "Schools",
        "SchoolDistricts",
        "DNROilGasWells",
        "TaxEntities2014"
    ]
- [x] SurfaceWaterQuality/MapService.MapServer": ["StreamsNHDHighRes"]
- [x] SurfaceWaterQuality/Toolbox.GPServer": ["StreamsNHDHighRes"]
- [x] [UtahPLSS.MapServer": ["PLSSTownships_GCDB", "PLSSSections_GCDB", "PLSSQuarterSections_GCDB", "PLSSQuarterQuarterSections_GCDB"]](https://github.com/agrc/PLSS/blob/master/scripts/PLSSPallet.py)

**Comment by stdavis** [comment]
Pretty sure that this issue can be closed. :confetti_ball:
