### ISSUE TITLE
Push reports to Slack

### ISSUE THREAD

**Issue by stdavis** [agrc/forklift#306]
I think that it would be cool to replace the daily report emails with automated posts to a slack channel. That way, our email inboxes won't be cluttered and those that are interested can just join the channel rather than having to edit the config file. Not sure if posting the log files would work.

**Comment by steveoh** [comment]
I would love to work on this. I don't believe we have any spots left for apps on the free plan but maybe a bot or slash command or something could work. I'm sure we could also make space or start to pay for the service.

https://cloud.google.com/functions/docs/tutorials/slack

@brigsz has there been any more talk of an enterprise slack?

**Comment by stdavis** [comment]
Closed in #313. I think that there could be improvements in the future, but overall, I think that the goal was accomplished.
