### ISSUE TITLE
Add arcpy.SignInToPortal

### ISSUE THREAD

**Issue by stdavis** [agrc/forklift#325]
We should add this to the beginning of forklift: https://pro.arcgis.com/en/pro-app/arcpy/functions/signintoportal.htm

**Comment by stdavis** [comment]
Or maybe this belongs in the AGOL Pallet? Not sure...

**Comment by stdavis** [comment]
This will be closed by: https://github.com/agrc/warehouse/pull/104

**Comment by steveoh** [comment]
Are we trying to solve pro being signed out when forklift runs?

**Comment by stdavis** [comment]
No since Pro on the server is licensed via a license manager. Just trying to prevent errors in the AGOL pallet that require Pro to be signed into AGOL for publishing/updating data.
