### ISSUE TITLE
Shut down service around remove/copy of data

### ISSUE THREAD

**Issue by steveoh** [agrc/forklift#45]
We need to test arcgis server to see what happens when we remove and copy data while it has a process spooled up. If it's ok then this issue can be closed.

Otherwise, a Pallet needs a property with the path to the service that can be used to restart the service.

I have a hunch, that we can remove and copy the fresh data and then restart the service. I'm hoping we do not need to stop the service to remove and copy.

The create schema lock setting might need to be set for all services.

**Comment by steveoh** [comment]
I'm currently creating two gdb's with a test feature class and publishing them to arcgis server as schema lock and no schema lock.

I'll then create a pallet to update their data and see what happens. I'll also try to query the rest endpoint to see what happens without a restart of the service.

**Comment by steveoh** [comment]
I was able to update the data on a service with and without a schema lock. The data update however did was not reflected in a rest query until the service was restarted.

How was this happening before @stdavis

**Comment by stdavis** [comment]
Closed with #52
