### ISSUE TITLE
cli

### ISSUE THREAD

**Issue by steveoh** [agrc/forklift#5]
I vote for [docopt](https://github.com/docopt/docopt) because it's awesome.

brainstorming ideas...

```py
'''
forklift
Usage:
  forklift update [--config=<config>]
  forklift update-only <path> [--plugin=<plugin>]
Options:
  --config     the path to some cfg or text file or something where we keep paths to places where there are update plugins. defaults to some relative or static path.
  --plugin     the name of the plugin used to filter execution. maybe a partial match or glob or exact match?
Arguments:
  <path>       an optional path to pass in so you can run a certain directory
'''
```

**Comment by stdavis** [comment]
So what's the difference between `update` and `update-only`? The ability to use a plugin?

**Comment by steveoh** [comment]
Update would run through all the update scripts. I envision that being the command the scheduled task calls. update-only would be a way that we could interact with forklift to say, i want to update-only parcels or broadband.

**Comment by stdavis** [comment]
OK. I get it now. I wonder if there is a better name tna update-only. Can't think of one right now. Maybe we can add a description for each of the methods in docopt. But ya, I like the concept a lot. There are lots of times that I want to manually run updates for a single project.

**Comment by steveoh** [comment]
what do you think about using forklift to add to the config and other things like that?

`forklift add-path <path>` to add to the config file etc?

**Comment by stdavis** [comment]
I think that could be useful. But only if it was smart enough not to add duplicates and maybe even have a command for listing the existing paths. Then I could see it actually saving time. But if it was me I would probably just leave it to hand editing the .json file. :)

**Comment by steveoh** [comment]
Yeah I was thinking it could be smart about the file, it could check that the path was accessible and existed and wasn't a duplicate etc. listing the config paths sounds nice too.
