### ISSUE TITLE
Create config file in the directory where forklift is invoked

### ISSUE THREAD

**Issue by stdavis** [agrc/forklift#63]
### Steps to reproduce
1. Run `forklift init`

### Expected behavior
`config.json` created in the folder from which forklift was invoked.

### Actual behavior
`config.json` is created in `site-packages`. This is nice in that it is in the same place no matter where you run forklift from but it's a pain to dig into that folder to take a look at the config file. It's also a bad place to be maintaining things in general. I think that it would be better to have it closer to where you are in the file system.

**Comment by steveoh** [comment]
I disagree. Forklift when pip installed can be run from anywhere. If the config is created in the working directory then we are going to have multiple configs or we are going to have to write more code to have that. I like that no matter what the config is going to be installed where forklift is installed.

**Comment by stdavis** [comment]
I can see your point. It just feels hacky to be editing a file in `site-packages`...

**Comment by steveoh** [comment]
I don't mind. What about a forklift config open command?

**Comment by stdavis** [comment]
I like that idea.

**Comment by stdavis** [comment]
So how are we going to deal with wanting to run two instances of forklift on the same machine? I can see us wanting to run forklift on .58 to update mapserv and also update data that the test apps are pointed at.

**Comment by steveoh** [comment]
uhh ohhhhhh.

have a flag for config setting and create a config.setting.json?

**Comment by stdavis** [comment]
`pip install -t` 👍
