### ISSUE TITLE
Tables getting OBJECTID_1 field

### ISSUE THREAD

**Issue by steveoh** [agrc/forklift#69]
### Steps to reproduce
1. create a pallet with a crate pointing to a table that is participating in a join
1. run forklift pointing to the pallet
1. look at the gdb table fields that was created

### Expected behavior
The table structure should be copied as is

### Actual behavior
OBJECTID_1 is created and causes issues on the second run of forklift.

If you need an example, i can repro this with the ACTS pallet I am creating so the data is coming from a 9.3 geodatabase.

Should OBJECTID_1 be added to the [naughty list](https://github.com/agrc/forklift/blob/bba5e3207c33488e48721c659f631741e8eb3105/src/forklift/core.py#L203)?

**Comment by stdavis** [comment]
I wasn't able to reproduce this bug with the fiber verification database. So, it must be more than just a table that participates in a relationship. Maybe it's the 9.3 thing? 

However, adding `OBJECTID_1` to the naughty list is OK with me. In fact, if we have other problems in the future we might add OBJECTID_*.

**Comment by steveoh** [comment]
Might have to do with an in memory operation then?

**Comment by stdavis** [comment]
Not sure. Although I always thought that in_memory was the same as any other in terms of functionality.

**Comment by steveoh** [comment]
> You'll see additional OBJECT IDs as a result of several gp operations that mash tables together. Is this an in_memory geoprocessing result by chance? The join is a likely suspect, though iirc the name of the file should be prepended to the attribute eg `layer.attribute`
