### ISSUE TITLE
Crates that update data in SDE have incorrect destination_name

### ISSUE THREAD

**Issue by stdavis** [agrc/forklift#70]
### Steps to reproduce
1. Run a pallet with a crate defined something like `('FCName', 'FGDB.gdb', 'SGID Stage.sde', 'SGID10.OWNER.FCName')`

### Expected behavior
`SGID Stage.sde/SGID10.OWNER.FCName` is updated or created.

### Actual behavior
`SGID Stage.sde/SGID10.OWNER.SGID10_OWNER_FCName` is updated or created. :(

I propose that the `.` -> `_` replacement only be done if `destination_name` is not passed into the constructor.

**Comment by steveoh** [comment]
Are you logging in with the owner? You shouldn't need the fully qualified name.   

Also wouldn't the result be db.owner.db_owner_nane?

**Comment by stdavis** [comment]
Yes, I am logging in as the owner. But I don't have the option of changing to the non-fully qualified name as there are other things built on the fully-qualified version (this is DEQ).

And yes, you're correct about the output. I've fixed the original description.
