### ISSUE TITLE
Field type schema check issues between FGDB and SDE

### ISSUE THREAD

**Issue by stdavis** [agrc/forklift#73]
### Steps to reproduce
1.  Copy a feature class with a field of type `Float` (shows `Single` in code) to an SDE database.
1.  Notice that the field type is now `Double` and curse ESRI.
1.  Run forklift on a pallet that defines a crate that moves data from the FGDB to SDE.

### Expected behavior
The schema check for the crate should pass successfully since it's the same feature class and no change to the schema have been made.

### Actual behavior
The schema check fails and reports something like: `AVE_LENGTH: source type of Single does not match destination type of Double`.

The issue is in this [line of code](https://github.com/agrc/forklift/blob/9d0377ad37d723fbe842295a3b9963ccf45022d1/src/forklift/core.py#L179). I propose that we run something like this before checking the field types:
```python
if not isTable:
    arcpy.MakeFeatureLayer_management(sdeFC, layer, '1 = 2')
else:
    arcpy.MakeTableView_management(sdeFC, layer, '1 = 2')

try:
    arcpy.Append_management(layer, f, 'TEST')
    passed = True
except:
    # go onto checking the field types and lengths for the report
```

I've tested Append_management against the Single/Double issue and it runs successfully.

**Comment by steveoh** [comment]
It must not care about adding precision. We could test the types like that also. Do you have a proposed solution with append_management or?

**Comment by stdavis** [comment]
My fix was to do the append as a test and only checking fields if it fails. But I'm running into troubles with it. What do you think about just validating generic types such as number, text, blob and date? Abstract Short integer, Long integer, Float, Double all into a generic number type? [Ref docs](http://desktop.arcgis.com/en/arcmap/10.3/manage-data/geodatabases/arcgis-field-data-types.htm)

**Comment by steveoh** [comment]
yup - that should work
