### ISSUE TITLE
core._has_changes giving false positives when comparing numeric fields

### ISSUE THREAD

**Issue by stdavis** [agrc/forklift#81]
### Steps to reproduce

Crate:

```
'destination_name': 'DWQMercuryInFishTissue',
'destination_workspace': 'SGID10 as ENVIRONMENT on stage.sde',
'source_name': 'Mercury_in_Fish_Tissue',
'source_workspace': '\\\\<...>\\GIS\\DWQGIS\\projects\\Interactive_Map\\DWQ_Data_Interactive_Map.gdb'
```

Run pallet two times in a row.
### Expected behavior

Result: "Created table successfully." on first run.
Result: "No changes found." on second run.
### Actual behavior

Result: "Created table successfully." on first run.
Result: "Data updated successfully." on second run.

Here's an example of the rows that were compared:

```
source row: (194.8000030517578, -111.941056, u'No Consumption Advisory', 41.501327, u'4900440 no fish advisory', u'Bluegill', 1, 0.1346, 189.1999969482422, u'BOX ELDER', 2013, u'4900440-Bluegill-2013', 10, 0.206, u'4900440', u'Reservoir/Lake', 0.08, 0.040219, u'MANTUA RES AB DAM 01', 4594839.0, 421458.0, (421458.0, 4594839.0))
destination row: (194.80000305, -111.941056, u'No Consumption Advisory', 41.501327, u'4900440 no fish advisory', u'Bluegill', 1, 0.1346, 189.19999695, u'BOX ELDER', 2013, u'4900440-Bluegill-2013', 10, 0.206, u'4900440', u'Reservoir/Lake', 0.08, 0.040219, u'MANTUA RES AB DAM 01', 4594839.0, 421458.0, (421458.0, 4594839.0))
```

**Comment by stdavis** [comment]
@steveoh: Did you confirm this was fixed? I tried it after the original hashing branch merge and it was still an issue. I haven't tried it recently.

**Comment by steveoh** [comment]
No I didn't but since things have been looking good and this was old I thought I'd clean up. Open this back up if you still think the is a problem.

**Comment by stdavis** [comment]
Tested this today and it's no longer a problem.

**Comment by steveoh** [comment]
DominantVegetation is a false positive right now I think.

**Comment by stdavis** [comment]
Oh really? What pallet is that in?

**Comment by steveoh** [comment]
Planning

**Comment by stdavis** [comment]
I wasn't able to reproduce on my machine:
![image](https://cloud.githubusercontent.com/assets/1326248/21595754/97ad9d0c-d0ee-11e6-982b-4a7c85dba08d.png)

**Comment by steveoh** [comment]
ok, maybe it was actually updated then but [i doubt it](https://gis.utah.gov/data/bioscience-overview/dominant-vegetation/). I scanned the report and saw it there and figured it has not been updated for some time.

**Comment by stdavis** [comment]
I'll reopen for now then.

**Comment by steveoh** [comment]
a couple of suspect updates... These updated twice in a row if I am remembering correctly. I verified the other recent updates were warranted.

```
Municipalities_Carto	Data updated successfully.
Municipalities	Data updated successfully.
```

**Comment by stdavis** [comment]
Is this still valid?
