### ISSUE TITLE
Git repos and pyc files

### ISSUE THREAD

**Issue by steveoh** [agrc/forklift#92]
I think I'm noticing something odd where a pallets source code can update but if there was a pyc file from a prior run, the old code is run. We may want to `git clean -f` to remove untracked files after our git update.

This could get rid of secret files or things that are git ignored right? So maybe we can delete all *.pyc files?

**Comment by stdavis** [comment]
I think that deleting all *.pyc files is the safer way to go. Although, I don't believe that I've run into this problem before.

**Comment by steveoh** [comment]
yeah I don't know how legit this is. Let's wait to see if you notice it happen to you.
