### ISSUE TITLE
Order by sql clause

### ISSUE THREAD

**Issue by steveoh** [agrc/forklift#93]
I think the problem here is objectid_1 and order by objectid

> RuntimeError: An invalid SQL statement was used. [SELECT OBJECTID_1, CustomerInfo_FK, Program, ContactPerson, GUID, DateFromPurchasing, ContactPhone, OriginalContractAmount, PDFDocument, ConEffectiveDate, ContactEmail, Fund, ReasonForRejection, PracticeMapPDF, NRCSNum, CancelDate, ArchPDF, Notes, UDAFContractNum, Dept, NEPAPDF, Cancelled, Project_FK, ScheduleOfOperationsPDF, ContractAmount, ReasonForCancellation, GrantCategory, ContractStatus, GranteeStatus, ConExpirationDate, OrgUnit, ManagerNotes, DateReceived, CostShareRate, ContractType, AppUnit, DateToPurchasing FROM ContractInformation ORDER BY OBJECTID]

**Comment by stdavis** [comment]
I don't think that this is an issue any more, is it?

**Comment by steveoh** [comment]
Nope!
