### ISSUE TITLE
Production Things Using Forklift

### ISSUE THREAD

**Issue by steveoh** [agrc/forklift#97]
### These are the apps that are currently using 🚜 in production

I _may_ be missing some and _some_ should be removed because they do not use fgdb's etc
- [x] https://broadband.utah.gov/map
- [x] https://locate.utah.gov/
- [x] https://crashmapping.utah.gov/
- [x] https://enviro.deq.utah.gov/
- [x] https://eqspillsps.deq.utah.gov/
- [x] https://grantreporting.udaf.utah.gov/
- [x] https://mapserv.utah.gov/SurfaceWaterQuality/
- [x] https://mapserv.utah.gov/bems/
- [x] https://mapserv.utah.gov/oilgasmining/
- [x] https://mapserv.utah.gov/parcles/
- [x] https://mapserv.utah.gov/planning/
- [x] https://mapserv.utah.gov/plss/
- [x] https://mapserv.utah.gov/raster/
- [x] https://mapserv.utah.gov/wvc/
- [x] http://geology.utah.gov/apps/waterchem
- [x] https://mapserv.utah.gov/vista (waiting to be pushed to production)
- [x] http://api.mapserv.utah.gov
### Update scripts being used in production
- [x] SGID10
- [x] udnr
- [x] udpr
- [x] FFSL
- [x] udwr
- [x] UEMP
- [x] uggp
- [x] ughp
- [x] ugio
- [x] UTAX
- [x] utrans

**Comment by stdavis** [comment]
What about the acts viewer? Not sure where that's hosted or what the domain is.

**Comment by steveoh** [comment]
I'm grouping that into https://grantreporting.udaf.utah.gov/. I have not republished the service yet because of #93

**Comment by stdavis** [comment]
I removed https://fiberediting.mapserv.utah.gov/map/ since it points directly at SDE and doesn't have any nightly script.

**Comment by stdavis** [comment]
I removed https://addressediting.utah.gov/ which doesn't use anything from FGDB's.

**Comment by stdavis** [comment]
@steveoh Any reason why we aren't deploying forklift to .54 so that api.mapserv.utah.gov is checked off of this list? Maybe worried about it working on 10.2?

**Comment by steveoh** [comment]
more so worried that the locator rebuild corrupts the locators

**Comment by stdavis** [comment]
With your work on the Locators pallet, can this issue be considered complete?

**Comment by steveoh** [comment]
![soon](http://media.riffsy.com/images/55b4fb70f1703a38fb8e5ac799050ccc/tenor.gif)

**Comment by stdavis** [comment]
Has the day finally come!?

**Comment by steveoh** [comment]
I need to repoint this to use the new locators soooo not yet.

**Comment by stdavis** [comment]
Are we there yet? :baby:

**Comment by steveoh** [comment]
🍰

**Comment by stdavis** [comment]
:balloon: :tada:
