### ISSUE TITLE
Use filename when scanning for pallets

### ISSUE THREAD

**Issue by stdavis** [agrc/forklift#99]
I wonder if we should only try to import potential pallets that have "palllet" in the file name. This would cut out all of the issues with running standalone scripts unintentionally. It would also make the import errors more relevant since they are more likely real issues. For example, last night the deq pallet failed to import (because I forgot to include a file that's not in version control) but the main forklift report didn't report any issues.

**Comment by steveoh** [comment]
I highly approve this idea
